name: Build and run sample

on:
  push:
    branches:
      - cpp-sample
  pull_request:
    branches:
      - cpp-sample

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run CMake and see if it builds
        run: |
          cmake -S . -B build
          cmake --build build
          
      - name: Run if Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: ./build/Debug/TestProject
      
      - name: Run if Not Windows
        if: ${{ matrix.os != 'windows-latest' }}
        run: ./build/TestProject
